import {sources,people as records} from './family-agent-service/relationships.js?v=20261005-crest';
(function () {
'use strict';
const people=records.filter(p=>/^person-\d+$/.test(p.id)).map(p=>[p.name,p.detail,p.source]);
let selected = 0;
function el(tag, text, cls) { const n=document.createElement(tag);if(text)n.textContent=text;if(cls)n.className=cls;return n; }
function showPerson(i) {
 selected=i;
 const p=people[i], parent=people[i+1], panel=document.getElementById('person-detail');panel.replaceChildren();
 panel.append(el('h3',p[0]),el('p',p[1],'small'));
 const family=p[2]==='family';
 panel.append(el('span',parent?(family?'Family testimony':'Published genealogy'):'Earlier path unresolved','badge'));
 panel.append(el('p',parent?p[0]+' is reported as the son of '+parent[0]+'.':'The path earlier than Tommaso is not reconstructed here. Lucio must not be attached as a verified ancestor.'));
 if(family) {
  panel.append(el('p','Paolo confirmed Guido as his father and Pompeo as his grandfather on 4 October 2026. This is attributed family testimony.'));
  const book=el('a','Libro d’Oro · XIX edition · p. 1257');book.href='#libro-doro-note';panel.append(book,el('p','The photographed book entry also names Guido as Paolo’s father. Guido’s birth year, 1900, is printed in the book and was confirmed by Paolo on 5 October 2026. This page does not name Guido’s father.','small'));
 }
 else if(p[2]!=='none') {
  const s=sources[p[2]],a=el('a',s[0]);a.href=s[1];a.target='_blank';a.rel='noopener noreferrer';panel.append(a);
  panel.append(el('p','A published compilation reports this relationship. Original supporting records have not yet been examined in this project.','small'));
 }
 panel.append(el('p','Title succession is not a sequence of parent–child relationships. A brother may inherit a title without becoming an ancestor.','small'));
 document.querySelectorAll('[data-person]').forEach(b=>b.setAttribute('aria-pressed',String(Number(b.dataset.person)===i)));
}
function renderLineage() {
 const all=document.getElementById('lineage-scope').value==='all',list=document.getElementById('lineage-list');list.replaceChildren();
 people.slice(0,all?people.length:6).forEach((p,i)=>{const li=el('li'),b=el('button');b.type='button';b.dataset.person=i;b.setAttribute('aria-pressed',String(i===selected));b.append(el('strong',p[0]),el('span',p[1]));b.addEventListener('click',()=>showPerson(i));li.append(b);list.append(li)});
 if(!all&&selected>5)selected=0;showPerson(selected);
}
document.getElementById('lineage-scope').addEventListener('change',renderLineage);renderLineage();
const stages=[
 ['Explorer · Assemble a candidate path','The first investigation located published Montecalvo genealogies and a recent pedigree naming Paolo. Paolo confirmed his father and grandfather. The explorer’s useful output is a relationship list with sources—not a claim that every link has been verified.'],
 ['Reviewer · Find the unresolved claim','The traditional Lucio account conflicts with a review of Davide Shamà’s historical research. The review challenges Lucio’s documentation. It also places the division into three branches centuries later, among Tommaso’s sons. No complete medieval path has been established here.'],
 ['Coordinator · Ask a better next question','Propose a bounded errand: obtain the relevant pages of Shamà’s study and the evidence cited for Lucio in traditional accounts. Record which relationships each source actually supports. A reviewer should compare those documents before deciding whether any disputed link can be accepted.']
];
function showStage(i){const d=document.getElementById('stage-detail');d.replaceChildren(el('h4',stages[i][0]),el('p',stages[i][1]));document.querySelectorAll('[data-stage]').forEach(b=>b.setAttribute('aria-pressed',String(Number(b.dataset.stage)===i)))}
document.querySelectorAll('[data-stage]').forEach(b=>b.addEventListener('click',()=>showStage(Number(b.dataset.stage))));showStage(0);
const errands={
 lucio:['Investigate the Lucio tradition','Compare the traditional identification of Lucio Pignatelli around 1102 with Davide Shamà’s 2009 study. We have read a review that challenges the identification, not the book or archival documents. Find the relevant pages and document references. Report what was directly examined, what was only reported by another writer, and what remains unresolved. Do not invent a chain to Lucio.'],
 records:['Check one Montecalvo relationship','Choose one parent–child link in the published Montecalvo genealogy. Locate an original civil, parish, marriage, or archival record supporting it. Record the person identities, date, archive, reference, and exact evidence for parentage. Distinguish title succession from descent. Return unresolved if the record is inaccessible or ambiguous.'],
 branches:['Compare two branch histories','Ask the participating branch heads to provide sourced paths to their earliest supported ancestors. Find proposed shared ancestors and check that they are the same people. Compare names, spouses, places, dates, and cited records. Preserve conflicting accounts. Prepare any request to a relative for approval; do not send messages automatically.']
};
document.querySelectorAll('[data-errand]').forEach(b=>b.addEventListener('click',()=>{const r=errands[b.dataset.errand],d=document.getElementById('errand-detail');d.hidden=false;d.replaceChildren(el('h3',r[0]),el('pre',r[1]),el('p','Copy this assignment into your AI assistant. This page has prepared instructions only; no agent or external request has been started.','small'))}));
function buildPrompt(v) {
 const goals={en:{lucio:'Investigate the proposed connection to Lucio Pignatelli, traditionally placed around 1102.',branch:'Find the earliest ancestor securely supported by the evidence available for my branch.',cousins:'Investigate a relationship between my branch and another family branch. Ask me which other branch before comparing.'},it:{lucio:'Indaga il collegamento proposto con Lucio Pignatelli, tradizionalmente collocato intorno al 1102.',branch:'Individua il più antico antenato sostenuto con sicurezza dalle prove disponibili per il mio ramo.',cousins:'Indaga il legame tra il mio ramo e un altro ramo familiare. Chiedimi quale altro ramo prima del confronto.'}};
 if(v.language==='it')return `ASSIGNMENT — RICERCA GENEALOGICA PIGNATELLI\nRamo: ${v.branch}\nPersona di partenza: ${v.person}\nTestimonianza fornita dal richiedente (da attribuire, non trattare come documento):\n${v.links||'Nessun legame ancora fornito.'}\n\nObiettivo: ${goals.it[v.goal]}\n\nOrganizza il lavoro in tre ruoli: ricercatore, revisore, coordinatore. Se sei un solo assistente, svolgi le fasi in sequenza e dichiaralo; non simulare agenti indipendenti.\n\n1. Ricercatore: trova fonti accessibili e costruisci una lista di rapporti genitore–figlio. Per ogni rapporto registra persone, fonte, pagina o riferimento archivistico, URL, prova e stato. Non dedurre una parentela dal cognome o dalla successione a un titolo.\n2. Revisore: controlla identità, cronologia e fonti copiate. Separa documenti originali, genealogie pubblicate, testimonianze familiari e ipotesi. Indica quali fonti hai letto e quali non puoi consultare. La tradizione su Lucio è contestata: confronta le prove senza presupporre il risultato.\n3. Coordinatore: restituisci la linea sostenuta dalle fonti, i punti controversi e fino a tre incarichi utili a colmare le lacune. Per ciascuno spiega la domanda, il documento necessario e come giudicare il risultato.\n\nNon inventare generazioni. Se non esiste un percorso verificabile, mostra dove si interrompe. Non contattare parenti o pubblicare dati senza autorizzazione specifica.\n\nRestituisci: tabella dei legami e fonti; contraddizioni e limiti; incarichi proposti; breve messaggio che io possa rivedere e condividere con i cugini.`;
 return `ASSIGNMENT — PIGNATELLI FAMILY RESEARCH\nBranch: ${v.branch}\nStarting person: ${v.person}\nRequester-supplied testimony (attribute it; do not treat it as an original record):\n${v.links||'No relationships supplied yet.'}\n\nGoal: ${goals.en[v.goal]}\n\nOrganize the work into explorer, reviewer, and coordinator roles. If you are one assistant, perform the stages sequentially and say so; do not pretend independent agents ran.\n\n1. Explorer: browse accessible sources and assemble parent–child relationships. For each link record the people, source, page or archival reference, URL, evidence, and status. Do not infer kinship from a surname or title succession.\n2. Reviewer: check identities, chronology, and copied sources. Separate original records, published genealogies, family testimony, and hypotheses. State which sources you actually read and which you could not access. The Lucio tradition is disputed: compare its evidence without assuming the conclusion.\n3. Coordinator: return the supported lineage, disputed links, and up to three useful errands arising from gaps. For each, explain the question, the evidence needed, and how to evaluate the result.\n\nNever invent generations. If no verified path exists, show where it stops. Do not contact relatives or publish information without specific authorization.\n\nReturn: a relationship-and-source table; contradictions and access limits; proposed errands; a short summary I can review and share with family members.`;
}
function generate(){const v={branch:document.getElementById('branch').value.trim(),person:document.getElementById('starting-person').value.trim(),links:document.getElementById('known-links').value.trim(),goal:document.getElementById('goal').value,language:document.getElementById('prompt-language').value};document.getElementById('agent-prompt').value=buildPrompt(v);document.getElementById('copy-status').textContent='Instructions ready. No agent has been started.'}
document.getElementById('branch-form').addEventListener('submit',e=>{e.preventDefault();generate()});generate();
document.getElementById('copy-prompt').addEventListener('click',async()=>{const p=document.getElementById('agent-prompt'),status=document.getElementById('copy-status');try{await navigator.clipboard.writeText(p.value);status.textContent='Instructions copied. Paste them into your AI assistant.'}catch(e){p.focus();p.select();status.textContent='Clipboard access is unavailable. The instructions are selected; copy them manually.'}});
document.getElementById('download-prompt').addEventListener('click',()=>{const blob=new Blob([document.getElementById('agent-prompt').value],{type:'text/plain;charset=utf-8'}),url=URL.createObjectURL(blob),a=el('a');a.href=url;a.download='pignatelli-agent-assignment.txt';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)});
const menu=document.querySelector('.hamburger'),nav=document.querySelector('.nav-menu');const observer=new MutationObserver(()=>menu.setAttribute('aria-expanded',String(nav.classList.contains('active'))));observer.observe(nav,{attributes:true,attributeFilter:['class']});
})();
