'use strict';
const form=document.getElementById('mission'),status=document.getElementById('run-status'),runButton=document.getElementById('run'),stopButton=document.getElementById('stop');
let controller=null,completed=null,seen=[];
function node(tag,text){const n=document.createElement(tag);n.textContent=text;return n;}
function renderOutput(element,text){element.replaceChildren();const pattern=/\[(recent|tradition|review|montecalvo)\]/g;let last=0;for(const m of text.matchAll(pattern)){element.append(document.createTextNode(text.slice(last,m.index)));const source=seen.find(s=>s.id===m[1]);if(source){const a=node('a',m[0]);a.href=source.finalUrl||source.url;a.target='_blank';a.rel='noopener noreferrer';element.append(a);}else element.append(document.createTextNode(m[0]));last=m.index+m[0].length;}element.append(document.createTextNode(text.slice(last)));}
function reset(){completed=null;seen=[];document.getElementById('report').hidden=true;document.getElementById('sources').replaceChildren();document.getElementById('read-count').textContent='No sources retrieved yet';document.querySelectorAll('[data-role]').forEach(card=>{card.classList.remove('running');card.querySelector('.state').textContent='Waiting';card.querySelector('.output').textContent='Waiting for this investigation.'});}
function event(e){if(e.type==='started')status.textContent=`Investigation started · ${e.model}`;
 if(e.type==='stage'){const card=document.querySelector(`[data-role="${e.role}"]`);card.classList.add('running');card.querySelector('.state').textContent='Working';status.textContent=`${e.role.charAt(0).toUpperCase()+e.role.slice(1)} is working…`;}
 if(e.type==='source'){seen.push(e.source);const li=node('li',''),a=node('a',e.source.title);a.href=e.source.url;a.target='_blank';a.rel='noopener noreferrer';li.append(a,node('span',e.source.status==='read'?'Read excerpts':'Unavailable'));li.lastChild.className='source-state';const detail=node('span',`${e.source.detail} Checked ${new Date(e.source.checkedAt).toLocaleString()}.`);detail.className='source-detail';li.append(detail);document.getElementById('sources').append(li);document.getElementById('read-count').textContent=`${seen.filter(s=>s.status==='read').length} read · ${seen.filter(s=>s.status!=='read').length} unavailable`;}
 if(e.type==='result'){const card=document.querySelector(`[data-role="${e.role}"]`);card.classList.remove('running');card.querySelector('.state').textContent='Completed · model output';renderOutput(card.querySelector('.output'),e.text);}
 if(e.type==='complete'){completed=e.run;document.getElementById('report').hidden=false;status.textContent=`Completed ${new Date(e.run.completedAt).toLocaleString()} · findings await family review`;}
 if(e.type==='error')throw new Error(e.message);
}
form.addEventListener('submit',async e=>{e.preventDefault();if(controller)return;reset();controller=new AbortController();runButton.disabled=true;stopButton.hidden=false;status.textContent='Connecting to the research team…';
 try{const r=await fetch('/api/research',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({goal:document.getElementById('goal').value,language:document.getElementById('language').value}),signal:controller.signal});
 if(!r.ok){const error=await r.json().catch(()=>({}));throw new Error(error.error||'The research service could not start.');}
 const reader=r.body.getReader(),decoder=new TextDecoder();let pending='';while(true){const {value,done}=await reader.read();pending+=decoder.decode(value||new Uint8Array(),{stream:!done});let pos;while((pos=pending.indexOf('\n'))>=0){const line=pending.slice(0,pos);pending=pending.slice(pos+1);if(line.trim())event(JSON.parse(line));}if(done)break;}
 if(!completed)throw new Error('The connection ended before all three agents finished. Partial findings remain unreviewed.');
 }catch(err){status.textContent=err.name==='AbortError'?'Stopped waiting. Partial findings remain unreviewed.':err.message;document.querySelectorAll('article.running').forEach(card=>{card.classList.remove('running');card.querySelector('.state').textContent='Stopped · incomplete';});}
 finally{controller=null;runButton.disabled=false;stopButton.hidden=true;}
});
stopButton.addEventListener('click',()=>controller?.abort());
function report(){return `PIGNATELLI FAMILY · LIVE AGENT INVESTIGATION\nRun: ${completed.id}\nQuestion: ${completed.goal}\nStarted: ${completed.startedAt}\nCompleted: ${completed.completedAt}\nModel: ${completed.model}\nStatus: Model findings awaiting family review\nLimits: ${completed.limits}\n\n${completed.stages.map(s=>s.role.toUpperCase()+'\n'+s.text).join('\n\n')}\n\nSOURCE ACCESS\n${completed.sources.map(s=>`[${s.id}] ${s.title}\n${s.finalUrl||s.url}\n${s.status} · ${s.checkedAt}\n${s.detail}`).join('\n\n')}\n\nUSAGE\n${JSON.stringify(completed.usage)}\n\nNo genealogy was changed and no relatives were contacted.\n`;}
document.getElementById('copy').addEventListener('click',async()=>{if(!completed)return;try{await navigator.clipboard.writeText(report());document.getElementById('report-status').textContent='Report copied.';}catch{document.getElementById('report-status').textContent='Clipboard unavailable. Download the report instead.';}});
document.getElementById('download').addEventListener('click',()=>{if(!completed)return;const url=URL.createObjectURL(new Blob([report()],{type:'text/plain;charset=utf-8'})),a=node('a','');a.href=url;a.download=`pignatelli-investigation-${completed.id}.txt`;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);});
