import test from 'node:test';
import assert from 'node:assert/strict';
import {readSource,runInvestigation,validateInput,plainText} from '../lib/agents.js';
test('only selected missions and languages enter the pilot',()=>{assert.deepEqual(validateInput({goal:'lucio',language:'it',extra:'ignored'}),{goal:'lucio',language:'it'});assert.throws(()=>validateInput({goal:'__proto__',language:'en'}));});
test('a tool cannot fetch an arbitrary URL or redirect off-source',async()=>{let count=0;const fetcher=async()=>{count++;return new Response('',{status:302,headers:{location:'http://127.0.0.1/private'}})};assert.equal((await readSource('http://127.0.0.1',fetcher)).status,'not_allowed');assert.equal(count,0);assert.equal((await readSource('recent',fetcher)).status,'unavailable');assert.equal(count,1);});
test('source failures are not promoted into read evidence',async()=>{assert.equal((await readSource('review',async()=>new Response('missing',{status:404}))).status,'unavailable');assert.equal(plainText('<script>invented ancestry</script><p>Lucio &amp; Tommaso</p>'),'Lucio & Tommaso');});
test('reviewer receives actual source failure and explorer output before coordinator runs',async()=>{const calls=[],events=[];const call=async body=>{calls.push(body);if(calls.length===1)return {output:[{type:'function_call',name:'read_family_source',call_id:'a',arguments:'{"source_id":"review"}'}]};return {output:[{type:'message',content:[{type:'output_text',text:'Unresolved. [review]'}]}],usage:{output_tokens:10}};};const result=await runInvestigation({goal:'lucio',language:'en'},{model:'test-model',call,read:async id=>({id,status:'unavailable',detail:'404'}),emit:e=>events.push(e)});assert.deepEqual(result.stages.map(s=>s.role),['explorer','reviewer','coordinator']);assert.equal(calls.length,4);assert.match(calls[2].input[0].content,/unavailable/);assert.match(calls[3].input[0].content,/reviewer/);assert.equal(result.sources[0].status,'unavailable');assert.ok(events.some(e=>e.type==='source'));});

test('historical mission stays within the two listed public evidence pages',()=>{assert.deepEqual(validateInput({goal:'history',language:'en'}),{goal:'history',language:'en'});});
